# syntax=docker/dockerfile:1 

FROM golang:1.19 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/api
RUN CGO_ENABLED=0 GOOS=linux go build -o /momo-backend

FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /momo-backend /momo-backend
EXPOSE 8081
ENTRYPOINT ["/momo-backend"]